# Generated by Django 5.2.11 on 2026-05-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="github_issue_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="github_issue_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="github_issue_state",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="feature",
            name="github_last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="feature",
            unique_together={("project", "github_issue_number")},
        ),
    ]
