# Generated by Django 5.2.11 on 2026-05-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_feature_github_issue_id_feature_github_issue_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={"ordering": ["status", "sort_order", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="feature",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
